### ISSUE TITLE
Commandtag Writefile does not support comma's

### ISSUE THREAD

**Issue by zpammer** [PhantomBot/PhantomBot#2892]
PhantomBot Version: 3.6.4 (stable) (Revision: https://github.com/PhantomBot/PhantomBot/commit/f414034edf673d256bb718fdd16937215371e63a)
O/S Version: Windows Server 2022 21H2
Java Version: windows build in 11.0.14.1+1
Web Browser Version (if Panel related): 1.6.8

Detailed Description:
I have the following command and the writefile does not seem to support any comma's.

``marteiNotes Ibra will test out a pizza with: (echo) (writefile pizza.txt, true, (sender) : (echo)) ``

Steps to Reproduce: See the command above

Logs:

``[08-14-2022 @ 17:14:44.612 GMT] [init.js:334] Error with Event Handler [command] Script [./commands/customCommands.js] Stacktrace [invalidLocation()@fileSystem.js:261 > writeToFile()@fileSystem.js:140 > writefile()@file.js:80 > tags()@commandTags.js:189 > customCommands.js:174 > init.js:326 > init.js:577] Exception [JavaException: java.nio.file.InvalidPathException: Illegal char <:> at index 40: ./addons/pizza.txt, true, Ibrahimovic_Z : test]``

Screenshots (if applicable): 
![image](https://user-images.githubusercontent.com/11378079/184547812-3839997a-6973-4c60-8a25-53a7dc8d1d08.png)

**Comment by zpammer** [comment]
That broke the entire writefile commandtag.
Below the error.

Command ``marteiNotes Ibra will test out a pizza with: (echo) (writefile pizza.txt, true, (sender) : (echo))``

``[08-19-2022 @ 07:51:33.650 GMT] [init.js:334] Error with Event Handler [command] Script [./commands/customCommands.js] Stacktrace [splitArgs()@misc.js:819 > writefile()@file.js:78 > tags()@commandTags.js:189 > customCommands.js:174 > init.js:326 > init.js:577] Exception [TypeError: Cannot find function replaceAll in object  pizza.txt, true, Ibrahimovic_Z : ascona apple on pizza.]``

Command ``(writefile test2.txt, true, 1)``

``[08-19-2022 @ 17:34:20.007 GMT] [init.js:334] Error with Event Handler [command] Script [./commands/customCommands.js] Stacktrace [splitArgs()@misc.js:819 > writefile()@file.js:78 > tags()@commandTags.js:189 > customCommands.js:174 > init.js:326 > init.js:577] Exception [TypeError: Cannot find function replaceAll in object  test2.txt, true, 1.]``
